title: <p align="center"> A Parmesh Yadav </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/parmesh10">GitHub</a>
  <br>   
  I'm loking for Data Science, Machine learning & NLP related jobs. 
  <br>
  </p>
theme: jekyll-theme-minimal
